# -*- coding: utf-8 -*-
"""Project5_GenderVoicesClassification_shravani

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvrP5ocqKpwFqI8SM0Ybp4_P-LzTnvvD

# Project 5: Gender Voices Classification

### Overview

In this project, you are provided with a dataset which contains some statistical information about the audio frequencies of different male and female voices. Based on the information provided, you have to find out which voice belongs to which gender using the `RandomForestClassifier` algorithm.

The data description is provided below for the dataset.

<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/project-4/gender_voice_dataset_attributes.png' width=600>

*Dataset credits: `https://www.mldata.io/dataset-details/gender_voice/`*

1. Train dataset 
  
  `https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/project-4/gender-voice-train.csv`

2. Test dataset 

  `https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/project-4/gender-voice-test.csv`

---

### Project Requirements

1. Create a pandas DataFrame for the train and test datasets.

2. Display the first five rows of both the training and test DataFrames.

3. Display the last five rows of both the training and test DataFrames.

4. Find the number of rows and columns in the train and test DataFrames.

5. Check for the missing values in the train and test DataFrames.

6. Count the number of `male` and `female` classes in the train DataFrame. 

7. Separate the feature variables, i.e., `x_train` and `x_test` from both the DataFrames.

8. Separate the target variable, i.e., `y_train` and `y_test` from both the DataFrames.

9. Apply the `RandomForestClassifier` machine learning model to predict the `males` and `female` classes in the test DataFrame, i.e, `x_test`.

10. Print the confusion matrix and the classification report to evaluate your prediction model. Also, based on the confusion matrix, precision, recall and f1-score values, report whether the prediction model deployed by you is making accurate predictions or not.

---

#### 1. Create The DataFrames

Create the Pandas DataFrames for both the training and test datasets.
"""

# Create the DataFrames for both the train and test datasets and store them in the 'train_df' and 'test_df' variables respectively.
import pandas as pd
train_df=pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/project-4/gender-voice-train.csv')
test_df=pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/project-4/gender-voice-test.csv')

"""---

#### 2. Display First Five Rows

Display the first five rows of both the `train_df` and `test_df` DataFrames.
"""

# Display the first 5 rows of the 'train_df' DataFrame.
train_df.head()

# Display the first 5 rows of the 'test_df' DataFrame.
test_df.head()

"""---

#### 3. Display Last Five Rows

Display the last five rows of both the `train_df` and `test_df` DataFrames.
"""

# Display the last 5 rows of the 'train_df' DataFrame.
train_df.tail()

# Display the last 5 rows of the 'test_df' DataFrame.
test_df.tail()

"""---

#### 4. Rows & Columns In Train DataFrame

Find the number of rows and columns in both the `train_df` and `test_df` DataFrames.
"""

# Print the number of rows and columns in both the DataFrames.
print(train_df.shape)
print(test_df.shape)

"""---

#### 5. Check For Missing Values 

Check whether any of the columns in both the `train_df` and `test_df` DataFrames has any missing value.
"""

# Check for the missing values in the 'train_df' DataFrame.
missing_values = 0
for column in train_df.columns:
  for item in train_df[column].isnull():
    if item == True:
      missing_values += 1

missing_values

# Check for the missing values in the 'test_df' DataFrame.
missing_values = 0
for column in test_df.columns:
  for item in test_df[column].isnull():
    if item == True:
      missing_values += 1

missing_values

"""---

#### 6. Count The `male` & `female` Classes

Find out the number of `male` and `female` values in both the `train_df` and `test_df` DataFrames.
"""

# Print the count of the 'male' and 'female' classes in the 'train_df' DataFrame.
train_df['label'].value_counts()

# Print the count of the 'male' and 'female' classes in the 'test_df' DataFrame.
test_df['label'].value_counts()

"""---

#### 7. Feature Variables Extraction

Get the feature variables, i.e., `x_train` and `x_test` from both the `train_df` and `test_df` DataFrames respectively. Then, display the first 5 rows of `x_train` and `x_test` DataFrames.
"""

# Get the feature variables from the 'train_df' DataFrame.
x_train=train_df.iloc[:, 1:]
# Display the first 5 rows of the 'x_train' DataFrame.
x_train.head()

# Get the feature variables from the 'test_df' DataFrame.
x_test=test_df.iloc[:,1:]
x_test.head()

# Display the first 5 rows of the 'x_test' DataFrame.

"""---

#### 8. Target Variable Extraction

Get the target variables, i.e., `y_train` and `y_test` from both the `train_df` and `test_df` DataFrames respectively. Then, display the first 5 rows of `y_train` and `y_test` Pandas series.
"""

# Get the target variable from the 'train_df' DataFrame.
y_train=train_df.iloc[:,0]
y_train.head()
# Display the first 5 rows of the 'y_train' Pandas series.

# Get the target variable from the 'test_df' DataFrame.
y_test=test_df.iloc[:,0]
# Display the first 5 rows of the 'y_test' Pandas series.
y_test.head()

"""---

#### 9. Building A Random Forest Classifier Model
"""

# Build a Random Forest Classifier model.
# Import the 'RandomForestClassifier' module.
from sklearn.ensemble import RandomForestClassifier
# Import the confusion_matrix and classification_report modules.
from sklearn.metrics import confusion_matrix,classification_report

# Predict the target variable based on the feature variables of the test DataFrame.
rf_clf = RandomForestClassifier(n_jobs=-1, n_estimators=50)
rf_clf.fit(x_train, y_train)
x_predicted=rf_clf.predict(x_test)
x_predicted

"""---

#### 10. Confusion Matrix & Classification Report

Print the confusion matrix and classification report to evaluate the model. Interpret and report the results obtained from the confusion matrix and the classification report.
"""

# Print the confusion matrix to see the number of TN, FN, TP and FP values.
confusion_matrix(y_test,x_predicted)

# Print the precision, recall and f1-score values for both the male and female classes.
print(classification_report(y_test,x_predicted))

"""**interpretation of the results here.**

- Interpretation 1: The precision, recall and f1 score values are nearly equal to one. this shows that the model can be classified as good model

- Interpretation 2: Resulted in quick analysis and interpretation of data

- Interpretation 3:

  $\dots$

- Interpretation N
"""